// Exact reviewed schema14/16 backup whitelist; actual SQLite PRAGMA parity is tested.
export const BACKUP_TABLES = [
  "app_meta", "c0_counters", "system_requests", "audit_events", "sync_outbox", "scheduled_jobs",
  "coaches", "settings", "seasons", "members", "migration_snapshots", "schedule_templates",
  "training_weeks", "practices", "practice_versions", "schedule_migration_snapshots", "signups",
  "signup_migration_snapshots", "seat_plan_states", "seat_plan_draft_seats", "seat_plan_revisions",
  "seat_plan_revision_seats", "seat_plan_revision_names", "seating_migration_snapshots",
  "practice_history", "history_corrections", "season_history", "history_migration_snapshots",
  "usage_snapshots", "sync_bindings", "sync_baselines", "source_imports", "sync_conflicts",
  "sync_batches", "sync_batch_items", "sync_migration_snapshots", "form_import_cursors",
  "form_import_receipts", "form_source_observations", "sync_export_controls",
  "sync_export_retries", "sync_associated_cursors", "sync_associated_physical_baselines",
  "sync_export_event_index", "sync_export_event_blocks", "sync_export_request_selections", "sync_export_poll_plans",
  "annual_archive_plans", "annual_archive_chunks", "annual_archive_requests", "source_authority_pins"
] as const;

export const BUSINESS_BACKUP_COLUMNS: Record<string, readonly string[]> = {
  app_meta: ["key","value"],
  c0_counters: ["counter_name","value"],
  system_requests: ["request_key","actor_scope","action","request_id","payload_digest","status","result_json","created_at","completed_at"],
  audit_events: ["event_id","request_key","actor_scope","action","details_json","created_at","season_id"],
  sync_outbox: ["outbox_id","request_key","topic","payload_json","status","due_at_ms","attempt_count","last_error","created_at","completed_at"],
  scheduled_jobs: ["job_id","job_type","payload_json","status","due_at_ms","attempt_count","lease_token","lease_until_ms","last_error","created_at","updated_at","completed_at"],
  coaches: ["coach_id","display_name","code_salt","code_digest","credential_version","active","created_at","updated_at"],
  settings: ["setting_key","value_json","settings_version","updated_at"],
  seasons: ["season_id","name","start_date","end_date","timezone","season_ends_at","status","binding_version","season_version","roster_version","created_by","created_at","updated_at"],
  members: ["season_id","member_id","source_key","source_display_name","display_name_override","status","default_preference","member_version","created_at","updated_at"],
  migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  schedule_templates: ["season_id","template_id","day_of_week","start_time","end_time","timezone","location","address","map_url","active","template_version","created_at","updated_at"],
  training_weeks: ["season_id","week_id","week_start_date","scheduled_open_at","status","week_version","confirmed_version","confirmed_by","confirmed_at","published_at","created_at","updated_at"],
  practices: ["season_id","practice_id","week_id","template_id","generation_key","start_at","end_at","timezone","location","address","map_url","left_capacity","right_capacity","signup_cutoff_at","practice_version","cancelled_at","cancelled_by","schedule_published_at","schedule_published_by","created_at","updated_at"],
  practice_versions: ["season_id","practice_id","signup_version","seat_plan_version","published_revision","signup_sequence"],
  schedule_migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  signups: ["season_id","practice_id","member_id","preference","status","queue_at","queue_sequence","updated_at","last_request_id"],
  signup_migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  seat_plan_states: ["season_id","practice_id","coach_member_id","steerer_member_id","updated_by","updated_at"],
  seat_plan_draft_seats: ["season_id","practice_id","side","row_number","member_id","seat_plan_version","updated_by","updated_at"],
  seat_plan_revisions: ["season_id","practice_id","revision_number","revision_id","source","seat_plan_version","coach_member_id","steerer_member_id","published_by","published_at","request_id"],
  seat_plan_revision_seats: ["season_id","practice_id","revision_number","side","row_number","member_id"],
  seat_plan_revision_names: ["season_id","practice_id","revision_number","member_id","display_name"],
  seating_migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  practice_history: ["season_id","practice_id","history_version","final_status","frozen_revision","snapshot_json","frozen_at"],
  history_corrections: ["season_id","practice_id","correction_id","history_version","note","created_by","created_at"],
  season_history: ["season_id","archive_year","practice_count","published_practice_count","snapshot_json","archived_at"],
  history_migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  usage_snapshots: ["usage_date","captured_at","database_size_bytes","request_count","audit_count","outbox_pending","jobs_pending","history_practice_count","history_season_count"],
  sync_bindings: ["season_id","binding_version","form_id","runtime_spreadsheet_id","response_sheet_id","response_sheet_name","field_mapping_json","schema_fingerprint","export_paused","last_pull_at","last_push_at","created_at","updated_at"],
  sync_baselines: ["season_id","binding_version","entity_type","entity_id","dependency_group","baseline_json","baseline_digest","cloud_version","sheet_digest","updated_at"],
  source_imports: ["stable_source_id","season_id","binding_version","source_type","source_external_id","source_digest","source_version","member_id","status","imported_at","updated_at"],
  sync_conflicts: ["conflict_id","season_id","binding_version","entity_type","entity_id","dependency_group","baseline_json","cloud_json","google_json","cloud_version","google_digest","status","created_at","resolved_at","resolution_json","finding_outcome","reason","row_number","fingerprint"],
  sync_batches: ["batch_id","season_id","binding_version","writer_epoch","direction","status","payload_digest","first_outbox_id","last_outbox_id","attempt_count","last_error","created_at","updated_at","completed_at"],
  sync_batch_items: ["batch_id","item_index","entity_type","entity_id","dependency_group","expected_sheet_digest","target_json","target_digest","status","receipt_json","updated_at"],
  sync_migration_snapshots: ["source_snapshot_id","payload_digest","imported_at","request_key"],
  form_import_cursors: ["season_id","binding_version","watermark_ms","window_start_ms","scan_baseline_ms","after_at_ms","after_id","last_read_at_ms","updated_at"],
  form_import_receipts: ["operation_id","request_key","season_id","binding_version","request_digest","response_digest","result_json","committed_at"],
  form_source_observations: ["stable_source_id","season_id","submitted_at","display_name","source_digest","review_reason","observed_at"],
  sync_export_controls: ["season_id","pause_requested","updated_at"],
  sync_export_retries: ["season_id","binding_version","failure_count","next_attempt_at_ms","last_error","updated_at","action_required"],
  sync_associated_cursors: ["season_id","binding_version","practice_id","signup_version","seat_plan_version","published_revision","updated_at"],
  sync_associated_physical_baselines: ["season_id","binding_version","scope","row_id","cells_json","cells_digest","updated_at"],
  sync_export_event_index: ["outbox_id","event_sequence","season_id","payload_anchor","topic_anchor","handler_kind","practice_id","classification_anchor","created_at"],
  sync_export_event_blocks: ["season_id","binding_version","outbox_id","practice_id","payload_anchor","payload_digest","error_code","failure_count","next_attempt_at_ms","action_required","blocked_scope","blocked_entity_id","created_at","updated_at"],
  sync_export_request_selections: ["request_key","season_id","binding_version","outbox_id","event_anchor","event_digest","request_digest","created_at"],
  sync_export_poll_plans: ["request_key","request_digest","plan_json","plan_digest","created_at"],
  annual_archive_plans: ["snapshot_id","logical_scope","first_request_key","first_request_id","actor_scope","command_text","command_digest","team_id","season_id","practice_id","kind","format","binding_version","backend_generation","writer_epoch","captured_at","cutoff_at","archive_year","status","metadata_text","canonical_plan_text","capture_proof_text","record_count","chunk_count","input_bytes","manifest_text","content_digest","completed_at"],
  annual_archive_chunks: ["snapshot_id","chunk_index","row_offset","row_count","payload_text","utf8_bytes","payload_digest"],
  annual_archive_requests: ["request_key","actor_scope","request_id","command_text","command_digest","snapshot_id","saved_result_text","created_at"],
  source_authority_pins: ["season_id","source_operation_id","actor_id","request_id","pin_text","authority_digest","pinned_at"],
};
